### ISSUE TITLE
Available on Chocolatey.org?

### ISSUE THREAD

**Issue by lboening** [claudiospizzi/ScriptConfig#5]
I use chocolatey.org. I see the package is not available there. Might you add?

**Comment by lboening** [comment]
Never mind. It is not so important. It was a short-cut for me to be able to easily install from Powershell 5 on Windows 7, which seems to support chocolatey as a provider.

**Comment by claudiospizzi** [comment]
No, I have no plans to release the module as a chocolatey package, because PowerShellGet is the de-facto standard for distributing PowerShell modules.

For older systems like Windows 7, you can check the PowerShellGet repo for an installer:
https://github.com/powershell/powershellget

Or just use PowerShell 5 (WMF 5.0 RTM) - PowerShellGet is part of this release and you can install the module with a single command:
```powershell
Install-Module -Name ScriptConfig
```

Thanks for using the module. If you have any issues or ideas, let me know.
